version: 2
updates:
  - package-ecosystem: gomod
    directory: /server
    schedule: { interval: weekly }
  - package-ecosystem: npm
    directory: /web
    schedule: { interval: weekly }
  - package-ecosystem: nuget
    directory: /clients/windows
    schedule: { interval: weekly }
  - package-ecosystem: gradle
    directory: /clients/android
    schedule: { interval: weekly }
  - package-ecosystem: github-actions
    directory: /
    schedule: { interval: weekly }
