<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="NSec.Cryptography" Version="24.4.0" />
    <PackageReference Include="System.Security.Cryptography.ProtectedData" Version="10.0.10" />
  </ItemGroup>
</Project>
