server {
    listen 80;
    listen [::]:80;
    server_name my-kul-01.vpn.tnestai.asia;

    location /.well-known/acme-challenge/ {
        root /var/www/html;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name my-kul-01.vpn.tnestai.asia;

    ssl_certificate /etc/letsencrypt/live/my-kul-01.vpn.tnestai.asia/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/my-kul-01.vpn.tnestai.asia/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;

    location = /latency {
        access_log off;
        add_header Cache-Control "no-store" always;
        add_header X-Content-Type-Options "nosniff" always;
        return 204;
    }

    location / {
        return 404;
    }
}
